version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
      ignore:
        - dependency-name: "tonic" #v0.13.1 causes breaking changes
        - dependency-name: "opentelemetry"
        - dependency-name: "opentelemetry_sdk"
        - dependency-name: "opentelemetry-otlp"
        - dependency-name: "opentelemetry-resource-detectors"
        - dependency-name: "opentelemetry-appender-tracing"

  # - package-ecosystem: "nuget"
  #   directory: "/"
  #   schedule:
  #     interval: "monthly"
